# Generated by Django 5.1.1 on 2025-03-29 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_mcuser_last_seen_at_mcuser_registered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(blank=True, null=True)),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='histories/images/')),
                ('content_video', models.FileField(blank=True, null=True, upload_to='histories/videos/')),
                ('content_audio', models.FileField(blank=True, null=True, upload_to='histories/audio/')),
                ('forwarded_post', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='users.mcuser')),
                ('viewed_by', models.ManyToManyField(blank=True, related_name='viewed_histories', to='users.mcuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
