# Generated by Django 5.1.1 on 2025-03-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_email_recipient_alter_email_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.EmailField(max_length=255),
        ),
    ]
