# Generated by Django 5.1.1 on 2025-02-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_miralnewsaccountprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miralnewsaccountprofile',
            name='profile_picture_url',
            field=models.FileField(default='pfps/default.png', upload_to='pfps'),
        ),
    ]
