# Generated by Django 5.1.1 on 2025-02-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_miralnewsaccountprofile_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miralnewsaccountprofile',
            name='profile_picture_url',
            field=models.FileField(default='pfps/avatar.png', upload_to='users/media/pfps'),
        ),
    ]
