# Generated by Django 5.1.1 on 2025-03-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_miralnewsaccountprofile_profile_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiralChatAccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=6)),
                ('about_me', models.CharField(max_length=255)),
                ('profile_picture_url', models.FileField(default='pfps/avatar.png', upload_to='pfps')),
                ('nickname', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mid',
        ),
        migrations.AlterField(
            model_name='miralnewsaccountprofile',
            name='profile_picture_url',
            field=models.FileField(default='pfps/avatar.png', upload_to='pfps'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('about_me', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture_url', models.FileField(blank=True, default='pfps/avatar.png', null=True, upload_to='pfps')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
