# Generated by Django 5.1.1 on 2025-03-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_miralchataccountprofile_mid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
