# Generated by Django 5.1.1 on 2025-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mid',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
