# Generated by Django 5.1.1 on 2025-03-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_chatuser_alter_miralchataccountprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(max_length=6000, upload_to='pictures')),
            ],
        ),
    ]
