# Generated by Django 5.1.1 on 2025-03-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_mcuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcuser',
            name='about',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mcuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
