# Generated by Django 5.1.1 on 2025-03-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_mcuser_about_alter_mcuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcuser',
            name='is_premium',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
