# Generated by Django 5.1.1 on 2025-04-03 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miral_cloud', '0001_initial'),
        ('users', '0014_mcuser_last_seen_at_mcuser_registered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mcuser')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='miral_cloud.group'),
        ),
    ]
